development:
 adapter: mysql2
 encoding: utf8
 database: assets
 username: root
 password: qburst
 host: localhost
 port: 3306

test:
 adapter: mysql2
 encoding: utf8
 database: assets
 username: root
 password: qburst
 host: localhost
 port: 3306